cluster: "~/.config/snakemake/{{cookiecutter.profile_name}}/slurm-submit.py --depend \"{dependencies}\""
cluster-status: "~/.config/snakemake/{{cookiecutter.profile_name}}/slurm-status.py"
jobscript: "slurm-jobscript.sh"
jobs: 500
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
use-singularity: true
use-envmodules: true
