cluster: "$((INSTALDIR))/slurm-submit.py --depend \"{dependencies}\""
cluster-status: "$((INSTALDIR))/slurm-status.py"
jobscript: "slurm-jobscript.sh"
jobs: 500
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
use-singularity: true
use-envmodules: true
