cluster: "~/.config/snakemake/{{cookiecutter.profile_name}}/slurm-submit.py {dependencies}"
jobscript: "slurm-jobscript.sh"
jobs: 500
verbose: {{cookiecutter.verbose}}
use-singularity: {{cookiecutter.use_singularity}}
use-envmodules: {{cookiecutter.use_envmodules}}
immediate-submit: {{cookiecutter.immediate_submit}}
notemp: true
