cluster: "~/.config/snakemake/cc-slurm/slurm-submit.py {dependencies}"
jobscript: "slurm-jobscript.sh"
jobs: 500
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
use-singularity: true
use-envmodules: true
